In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

daily_activity = pd.read_csv("Cleaned/dailyActivity_cleaned.csv")
sleep_day = pd.read_csv("Cleaned/sleepDay_cleaned.csv")
hourly_steps = pd.read_csv("Cleaned/hourlySteps_cleaned.csv")
hourly_intensities = pd.read_csv("Cleaned/hourlyIntensities_cleaned.csv")

In [4]:
daily_activity[
    [
        "TotalSteps",
        "TotalDistance",
        "Calories",
        "VeryActiveMinutes",
        "FairlyActiveMinutes",
        "LightlyActiveMinutes",
        "SedentaryMinutes"
    ]
].describe().round(2)

,TotalSteps,TotalDistance,Calories,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes
count,940.00,940.00,940.00,940.00,940.00,940.00,940.00
mean,7637.91,5.49,2303.61,21.16,13.56,192.81,991.21
std,5087.15,3.92,718.17,32.84,19.99,109.17,301.27
min,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,3789.75,2.62,1828.50,0.00,0.00,127.00,729.75
50%,7405.50,5.24,2134.00,4.00,6.00,199.00,1057.50
75%,10727.00,7.71,2793.25,32.00,19.00,264.00,1229.50
max,36019.00,28.03,4900.00,210.00,143.00,518.00,1440.00

In [5]:
sleep_day[
    [
        "TotalSleepHours",
        "TimeInBedHours"
    ]
].describe().round(2)

       TotalSleepHours  TimeInBedHours
count           410.00          410.00
mean              6.99            7.64
std               1.98            2.12
min               0.97            1.02
25%               6.02            6.73
50%               7.21            7.72
75%               8.17            8.77
max              13.27           16.02

In [6]:
daily_activity["ActivityLevel"].value_counts()

ActivityLevel
Moderate    334
High        303
Low         303
Name: count, dtype: int64

In [7]:
activity_distribution = (
    daily_activity["ActivityLevel"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print(activity_distribution)

ActivityLevel
Moderate    35.53
High        32.23
Low         32.23
Name: proportion, dtype: float64

In [8]:
weekday_order = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday"
]

weekday_analysis = (
    daily_activity
    .groupby("DayOfWeek")
    .agg(
        AvgSteps=("TotalSteps", "mean"),
        AvgCalories=("Calories", "mean"),
        AvgSedentaryMinutes=("SedentaryMinutes", "mean"),
        AvgActiveMinutes=("TotalActiveMinutes", "mean")
    )
    .reindex(weekday_order)
    .round(2)
)

weekday_analysis

           AvgSteps  AvgCalories  AvgSedentaryMinutes  AvgActiveMinutes
DayOfWeek
Monday      7780.87      2324.21              1027.94            229.17
Tuesday     8125.01      2356.01              1007.36            234.63
Wednesday   7559.37      2302.62               989.48            223.73
Thursday    7405.84      2199.57               961.99            216.79
Friday      7448.23      2331.79              1000.31            236.37
Saturday    8152.98      2354.97               964.28            244.27
Sunday      6933.23      2263.00               990.26            208.49

In [9]:
print(
    "Most active day:",
    weekday_analysis["AvgSteps"].idxmax()
)

print(
    "Least active day:",
    weekday_analysis["AvgSteps"].idxmin()
)

Most active day: Saturday
Least active day: Sunday

In [10]:
hourly_analysis = (
    hourly_steps
    .groupby("Hour")
    .agg(
        AvgSteps=("StepTotal", "mean")
    )
)

hourly_analysis

        AvgSteps
Hour
0      42.188437
1      23.102894
2      17.110397
3       6.426581
4      12.699571
5      43.869099
6     178.508056
7     306.049409
8     427.544576
9     433.301826
10    481.665231
11    456.886731
12    548.642082
13    537.698154
14    540.513572
15    406.319126
16    496.845645
17    550.232892
18    599.169978
19    583.390728
20    353.905077
21    308.138122
22    237.987832
23    122.132890

In [11]:
peak_hour = hourly_analysis["AvgSteps"].idxmax()

print("Peak activity hour:", peak_hour)

Peak activity hour: 18

In [12]:
print(
    hourly_analysis.sort_values(
        "AvgSteps",
        ascending=False
    ).head(5)
)

        AvgSteps
Hour
18    599.169978
19    583.390728
17    550.232892
12    548.642082
14    540.513572

In [13]:
sleep_analysis = (
    sleep_day
    .agg(
        AvgSleepHours=("TotalSleepHours", "mean"),
        MedianSleepHours=("TotalSleepHours", "median"),
        AvgTimeInBed=("TimeInBedHours", "mean")
    )
)

sleep_analysis.round(2)

                  TotalSleepHours  TimeInBedHours
AvgSleepHours                6.99             NaN
MedianSleepHours             7.21             NaN
AvgTimeInBed                  NaN            7.64

In [14]:
weekday_sleep = (
    sleep_day
    .groupby("DayOfWeek")
    .agg(
        AvgSleepHours=("TotalSleepHours", "mean"),
        AvgTimeInBed=("TimeInBedHours", "mean")
    )
    .reindex(weekday_order)
    .round(2)
)

weekday_sleep

           AvgSleepHours  AvgTimeInBed
DayOfWeek
Monday              6.99          7.62
Tuesday             6.74          7.39
Wednesday           7.24          7.83
Thursday            6.69          7.25
Friday              6.76          7.42
Saturday            6.98          7.66
Sunday              7.55          8.39

In [15]:
activity_sleep = pd.read_csv(
    "Cleaned/activity_sleep_analysis.csv"
)

In [16]:
activity_sleep[
    [
        "TotalSteps",
        "VeryActiveMinutes",
        "FairlyActiveMinutes",
        "LightlyActiveMinutes",
        "SedentaryMinutes",
        "TotalSleepHours"
    ]
].corr().round(2)

,TotalSteps,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,TotalSleepHours
TotalSteps,1.00,0.54,0.57,0.42,-0.13,-0.19
VeryActiveMinutes,0.54,1.00,0.32,-0.20,-0.02,-0.09
FairlyActiveMinutes,0.57,0.32,1.00,-0.02,-0.04,-0.25
LightlyActiveMinutes,0.42,-0.20,-0.02,1.00,-0.26,0.03
SedentaryMinutes,-0.13,-0.02,-0.04,-0.26,1.00,-0.60
TotalSleepHours,-0.19,-0.09,-0.25,0.03,-0.60,1.00

In [17]:
print(
    "Steps vs Sleep:",
    round(
        activity_sleep["TotalSteps"]
        .corr(activity_sleep["TotalSleepHours"]),
        2
    )
)

Steps vs Sleep: -0.19

In [18]:
summary = {
    "Metric": [
        "Average Daily Steps",
        "Average Calories",
        "Average Sedentary Minutes",
        "Average Active Minutes",
        "Average Sleep Hours",
        "Peak Activity Hour"
    ],
    "Value": [
        daily_activity["TotalSteps"].mean(),
        daily_activity["Calories"].mean(),
        daily_activity["SedentaryMinutes"].mean(),
        daily_activity["TotalActiveMinutes"].mean(),
        sleep_day["TotalSleepHours"].mean(),
        hourly_steps.groupby("Hour")["StepTotal"].mean().idxmax()
    ]
}

summary_df = pd.DataFrame(summary)

summary_df

                      Metric        Value
0        Average Daily Steps  7637.910638
1           Average Calories  2303.609574
2  Average Sedentary Minutes   991.210638
3     Average Active Minutes   227.542553
4        Average Sleep Hours     6.986220
5         Peak Activity Hour    18.000000

In [19]:
activity_sleep = pd.read_csv(
    "Cleaned/activity_sleep_analysis.csv"
)

activity_sleep.head()

,Id,Date,TotalSteps,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,TotalSleepHours
0,1503960366,2016-04-12,13162,25,13,328,728,5.450000
1,1503960366,2016-04-13,10735,21,19,217,776,6.400000
2,1503960366,2016-04-15,9762,29,34,209,726,6.866667
3,1503960366,2016-04-16,12669,36,10,221,773,5.666667
4,1503960366,2016-04-17,9705,38,20,164,539,11.666667

In [20]:
correlation = activity_sleep["TotalSteps"].corr(
    activity_sleep["TotalSleepHours"]
)

print("Steps vs Sleep correlation:", correlation)

Steps vs Sleep correlation: -0.19034391666763167

In [25]:
daily_activity.groupby("ActivityLevel").agg(
    AvgSteps=("TotalSteps", "mean"),
    AvgSedentaryMinutes=("SedentaryMinutes", "mean"),
    AvgActiveMinutes=("TotalActiveMinutes", "mean"),
    AvgCalories=("Calories", "mean")
).round(2)

               AvgSteps  AvgSedentaryMinutes  AvgActiveMinutes  AvgCalories
ActivityLevel
High           13337.40               888.66            313.76      2743.58
Low             2128.17              1132.47             92.52      1806.81
Moderate        7465.78               956.09            271.81      2355.16

In [26]:
final_kpis = pd.DataFrame({
    "Metric": [
        "Average Daily Steps",
        "Average Calories",
        "Average Sedentary Minutes",
        "Average Active Minutes",
        "Average Sleep Hours",
        "Peak Activity Hour",
        "Most Active Day",
        "Least Active Day",
        "Steps vs Sleep Correlation"
    ],
    "Value": [
        daily_activity["TotalSteps"].mean(),
        daily_activity["Calories"].mean(),
        daily_activity["SedentaryMinutes"].mean(),
        daily_activity["TotalActiveMinutes"].mean(),
        sleep_day["TotalSleepHours"].mean(),
        hourly_analysis["AvgSteps"].idxmax(),
        weekday_analysis["AvgSteps"].idxmax(),
        weekday_analysis["AvgSteps"].idxmin(),
        activity_sleep["TotalSteps"].corr(
            activity_sleep["TotalSleepHours"]
        )
    ]
})

final_kpis

                       Metric        Value
0         Average Daily Steps  7637.910638
1            Average Calories  2303.609574
2   Average Sedentary Minutes   991.210638
3      Average Active Minutes   227.542553
4         Average Sleep Hours      6.98622
5          Peak Activity Hour           18
6             Most Active Day     Saturday
7            Least Active Day       Sunday
8  Steps vs Sleep Correlation    -0.190344

In [27]:
final_kpis.to_csv(
    "Cleaned/final_kpis.csv",
    index=False
)